---
- import_tasks: 'setup_packages.yml'
- import_tasks: 'setup_security.yml'

- name: Run update-alternatives
  command: "/usr/bin/env update-alternatives --set {{ item.name }} {{ item.path }}"
  with_items: "{{ ubuntu_update_alternatives }}"
  register: command_result
  changed_when: "command_result.stdout != ''"
