---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - vars/{{ ansible_distribution_version | lower }}.yml

- import_tasks: 'setup_packages.yml'
- import_tasks: 'setup_users.yml'
- import_tasks: 'setup_misc.yml'
