---

- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: present
    create_home: yes
    comment: "{{ item.comment | default('Created by Ansible') }}"
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Setup authorized_keys for users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
    state: present
  when: item.key is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Config users as sudoers
  lineinfile: "dest=/etc/sudoers
    insertafter=EOF
    line='{{ item.username }} ALL=(ALL) NOPASSWD:ALL'
    regexp='^{{ item.username }} .*'
    state=present"
  when:
    - item.use_sudo is defined
    - '{{ item.use_sudo }} == True'
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Setup .vimrc for users
  template:
    src: vimrc.j2
    dest: "/home/{{ item.username }}/.vimrc"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0640
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Setup .my.cnf for users
  template:
    src: my.cnf.j2
    dest: "/home/{{ item.username }}/.my.cnf"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Setup .profile for users
  template:
    src: profile.j2
    dest: "/home/{{ item.username }}/.profile"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'
