---

- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: present
    create_home: yes
    comment: "{{ item.comment | default('Created by Ansible') }}"
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Setup users ssh login key
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
    state: present
  when: item.key is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Config users as sudoers
  lineinfile: "dest=/etc/sudoers
    insertafter=EOF
    line='{{ item.username }} ALL=(ALL) NOPASSWD:ALL'
    regexp='^{{ item.username }} .*'
    state=present"
  when:
    - item.use_sudo is defined
    - '{{ item.use_sudo }} == True'
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Copy .vimrc into users
  copy:
    src: files/vimrc
    dest: "/home/{{ item.username }}/.vimrc"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Copy .my.cnf into users
  copy:
    src: files/my.cnf
    dest: "/home/{{ item.username }}/.my.cnf"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Create users .profile
  file:
    path: "/home/{{ item.username }}/.profile"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
    state: touch
  when: item.username is defined
  with_items: '{{ ubuntu_users | default([]) }}'

- name: Config users .profile
  blockinfile:
    path: "/home/{{ item.username }}/.profile"
    block: |
      export LANGUAGE=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LC_ALL=en_US.UTF-8
  with_items: '{{ ubuntu_users | default([]) }}'
