---
- name: Update Packages List
  apt: update_cache=true
  register: update_packages_list

- name: Install Packages
  apt:
    pkg: "{{ ubuntu_packages }}"
    state: latest
  when: update_packages_list is success

- name: Install Packages via deb
  apt:
    deb: "{{ item }}"
  with_items: "{{ ubuntu_deb_package_urls }}"
  when: update_packages_list is success
